language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test -- --coverage
  - npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash)
